[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
	'account-abstraction/=lib/account-abstraction/contracts/',
	'@chainlink/=lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/',
]
solc_version = '0.8.23'
bytecode_hash = "none"
cbor_metadata = false
optimize = true
via-ir = true
runs = 1000000

gas_reports = ["Kernel", "KernelLiteECDSA", "KernelFactory"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
